import { z } from 'zod'
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import type { ReceiptEngine } from '../engine/receipt-engine.js'

export function registerTrackAction(server: McpServer, engine: ReceiptEngine): void {
  server.tool(
    'track_action',
    'Create a completed Ed25519-signed receipt for an AI agent action with automatic SHA-256 hashing of input and output data. Records model usage, costs, latency, and constraint evaluations. Returns the signed receipt with receipt_id for future reference. Use this as the primary tool for recording agent actions — prefer over create_receipt + complete_receipt for single-step actions.',
    {
      action: z.string().describe('Action name being recorded (e.g., "generate_code", "summarize_text", "classify_intent")'),
      input: z.unknown().describe('Input data passed to the agent — automatically hashed with SHA-256, raw data is never stored'),
      output: z.unknown().optional().describe('Output produced by the agent — automatically hashed with SHA-256, raw data is never stored'),
      output_summary: z.string().optional().describe('Human-readable summary of the output for audit purposes (max 500 chars recommended)'),
      model: z.string().optional().describe('AI model used (e.g., "claude-sonnet-4-20250514", "gpt-4o", "gemini-2.0-flash")'),
      tokens_in: z.number().int().nonnegative().optional().describe('Input tokens consumed by the model'),
      tokens_out: z.number().int().nonnegative().optional().describe('Output tokens generated by the model'),
      cost_usd: z.number().nonnegative().optional().describe('Execution cost in USD (e.g., 0.0045)'),
      latency_ms: z.number().int().nonnegative().optional().describe('Total execution time in milliseconds'),
      tool_calls: z.array(z.string()).optional().describe('Names of tools called during this action (e.g., ["web_search", "code_exec"])'),
      tags: z.array(z.string()).optional().describe('Arbitrary tags for filtering and categorization (e.g., ["production", "critical"])'),
      confidence: z.number().min(0).max(1).optional().describe('Confidence score for the output quality, 0.0 to 1.0'),
      metadata: z.record(z.unknown()).optional().describe('Arbitrary key-value metadata attached to the receipt'),
      parent_receipt_id: z.string().optional().describe('Parent receipt ID for chaining — links this receipt to a previous step'),
      chain_id: z.string().optional().describe('Chain identifier for grouping related receipts — auto-generated if not provided'),
      constraints: z.array(z.object({
        type: z.string().min(1),
        value: z.unknown(),
        message: z.string().optional(),
      })).optional().describe('Constraint definitions to evaluate against this receipt (e.g., max_latency_ms, max_cost_usd, min_confidence)'),
      expires_at: z.string().datetime().optional().describe('ISO 8601 datetime when this receipt expires (e.g., "2026-12-31T23:59:59Z")'),
      ttl_ms: z.number().positive().optional().describe('Time-to-live in milliseconds from now — alternative to expires_at'),
    },
    async (params) => {
      const receipt = await engine.track(params)
      const response: Record<string, unknown> = { receipt }
      if (receipt.constraint_result && typeof receipt.constraint_result === 'object' && 'passed' in receipt.constraint_result) {
        const cr = receipt.constraint_result as { passed: boolean; results: unknown[] }
        response.constraints_passed = cr.passed
        response.constraint_summary = `${cr.results.filter((r: unknown) => (r as { passed: boolean }).passed).length}/${cr.results.length} passed`
      }
      return {
        content: [{ type: 'text' as const, text: JSON.stringify(response, null, 2) }],
      }
    },
  )
}
