import type { Entity, Observation, Relationship } from '@agent-receipts/schema'
import type { ActionReceipt } from '@agent-receipts/schema'

// ─── Entities ───────────────────────────────────────────────────────────────

export const DEMO_ENTITIES: Entity[] = [
  {
    entity_id: 'ent_demo_001',
    entity_type: 'person',
    name: 'Alex Chen',
    aliases: ['alex', 'achen'],
    scope: 'user',
    created_at: '2026-03-01T10:00:00Z',
    created_by_agent: 'agent-alpha',
    created_by_receipt: 'rcpt_mem_001',
    forgotten_at: null,
    merged_into: null,
    attributes: { role: 'lead engineer', team: 'platform' },
    metadata: {},
  },
  {
    entity_id: 'ent_demo_002',
    entity_type: 'project',
    name: 'Horizon API',
    aliases: ['horizon', 'horizon-api'],
    scope: 'team',
    created_at: '2026-03-01T11:30:00Z',
    created_by_agent: 'agent-alpha',
    created_by_receipt: 'rcpt_mem_002',
    forgotten_at: null,
    merged_into: null,
    attributes: { language: 'TypeScript', repo: 'nebula-labs/horizon-api' },
    metadata: {},
  },
  {
    entity_id: 'ent_demo_003',
    entity_type: 'tool',
    name: 'PostgreSQL',
    aliases: ['postgres', 'pg'],
    scope: 'team',
    created_at: '2026-03-02T09:15:00Z',
    created_by_agent: 'agent-beta',
    created_by_receipt: 'rcpt_mem_003',
    forgotten_at: null,
    merged_into: null,
    attributes: { version: '16.2' },
    metadata: {},
  },
  {
    entity_id: 'ent_demo_004',
    entity_type: 'preference',
    name: 'Code Style',
    aliases: ['coding-style', 'style-guide'],
    scope: 'user',
    created_at: '2026-03-02T14:20:00Z',
    created_by_agent: 'agent-alpha',
    created_by_receipt: 'rcpt_mem_004',
    forgotten_at: null,
    merged_into: null,
    attributes: {},
    metadata: {},
  },
  {
    entity_id: 'ent_demo_005',
    entity_type: 'organization',
    name: 'Nebula Labs',
    aliases: ['nebula'],
    scope: 'team',
    created_at: '2026-03-03T08:00:00Z',
    created_by_agent: 'agent-alpha',
    created_by_receipt: 'rcpt_mem_005',
    forgotten_at: null,
    merged_into: null,
    attributes: { industry: 'developer-tools', size: '50-200' },
    metadata: {},
  },
  {
    entity_id: 'ent_demo_006',
    entity_type: 'tool',
    name: 'TypeScript',
    aliases: ['ts'],
    scope: 'user',
    created_at: '2026-03-03T10:45:00Z',
    created_by_agent: 'agent-gamma',
    created_by_receipt: 'rcpt_mem_006',
    forgotten_at: null,
    merged_into: null,
    attributes: { version: '5.4' },
    metadata: {},
  },
  {
    entity_id: 'ent_demo_007',
    entity_type: 'context',
    name: 'Q1 Sprint',
    aliases: ['q1-sprint', 'sprint-q1-2026'],
    scope: 'team',
    created_at: '2026-03-04T09:00:00Z',
    created_by_agent: 'agent-alpha',
    created_by_receipt: 'rcpt_mem_007',
    forgotten_at: null,
    merged_into: null,
    attributes: { quarter: 'Q1', year: 2026 },
    metadata: {},
  },
  {
    entity_id: 'ent_demo_008',
    entity_type: 'person',
    name: 'Sarah Kim',
    aliases: ['sarah', 'skim'],
    scope: 'team',
    created_at: '2026-03-05T11:00:00Z',
    created_by_agent: 'agent-beta',
    created_by_receipt: 'rcpt_mem_008',
    forgotten_at: null,
    merged_into: null,
    attributes: { role: 'product manager' },
    metadata: {},
  },
  {
    entity_id: 'ent_demo_009',
    entity_type: 'tool',
    name: 'Webpack',
    aliases: ['wp'],
    scope: 'user',
    created_at: '2026-03-06T15:00:00Z',
    created_by_agent: 'agent-alpha',
    created_by_receipt: 'rcpt_mem_009',
    forgotten_at: '2026-03-20T16:00:00Z',
    merged_into: null,
    attributes: { version: '5.90' },
    metadata: {},
  },
]

// ─── Observations ───────────────────────────────────────────────────────────

export const DEMO_OBSERVATIONS: Observation[] = [
  // Alex Chen — 8 observations
  {
    observation_id: 'obs_demo_001',
    entity_id: 'ent_demo_001',
    content: 'Alex prefers functional programming patterns over OOP where possible',
    confidence: 'high',
    source_receipt_id: 'rcpt_mem_001',
    source_agent_id: 'agent-alpha',
    source_context: 'code review conversation',
    observed_at: '2026-03-01T10:05:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['preference', 'coding'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_002',
    entity_id: 'ent_demo_001',
    content: 'Alex is the tech lead for the Horizon API project',
    confidence: 'certain',
    source_receipt_id: 'rcpt_mem_001',
    source_agent_id: 'agent-alpha',
    source_context: 'project kickoff',
    observed_at: '2026-03-01T10:10:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['role', 'project'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_003',
    entity_id: 'ent_demo_001',
    content: 'Alex uses Neovim as primary editor with custom LSP configuration',
    confidence: 'high',
    source_receipt_id: 'rcpt_mem_010',
    source_agent_id: 'agent-alpha',
    source_context: 'pair programming session',
    observed_at: '2026-03-03T14:30:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['tooling'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_004',
    entity_id: 'ent_demo_001',
    content: 'Alex prefers concise PR descriptions with bullet points',
    confidence: 'medium',
    source_receipt_id: 'rcpt_mem_010',
    source_agent_id: 'agent-gamma',
    source_context: 'PR review',
    observed_at: '2026-03-05T09:20:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['preference', 'workflow'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_005',
    entity_id: 'ent_demo_001',
    content: 'Alex is on PTO March 25-28',
    confidence: 'certain',
    source_receipt_id: 'rcpt_mem_011',
    source_agent_id: 'agent-alpha',
    source_context: 'calendar sync',
    observed_at: '2026-03-10T08:00:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: '2026-03-25T00:00:00Z',
    tags: ['schedule'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_006',
    entity_id: 'ent_demo_001',
    content: 'Alex previously used VS Code but switched to Neovim in January 2026',
    confidence: 'medium',
    source_receipt_id: 'rcpt_mem_010',
    source_agent_id: 'agent-alpha',
    source_context: 'conversation',
    observed_at: '2026-03-03T14:35:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: 'obs_demo_003',
    expires_at: null,
    tags: ['tooling'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_007',
    entity_id: 'ent_demo_001',
    content: 'Alex timezone is Pacific Time (PT)',
    confidence: 'certain',
    source_receipt_id: 'rcpt_mem_001',
    source_agent_id: 'agent-beta',
    source_context: 'team standup',
    observed_at: '2026-03-02T09:00:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['schedule'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_008',
    entity_id: 'ent_demo_001',
    content: 'Alex completed the AWS Solutions Architect certification',
    confidence: 'high',
    source_receipt_id: 'rcpt_mem_012',
    source_agent_id: 'agent-alpha',
    source_context: 'slack channel',
    observed_at: '2026-03-12T16:00:00Z',
    forgotten_at: '2026-03-18T10:00:00Z',
    forgotten_by: 'agent-alpha',
    superseded_by: null,
    expires_at: null,
    tags: ['certification'],
    metadata: {},
  },

  // Horizon API — 5 observations
  {
    observation_id: 'obs_demo_009',
    entity_id: 'ent_demo_002',
    content: 'Horizon API uses Express.js with a layered architecture pattern',
    confidence: 'certain',
    source_receipt_id: 'rcpt_mem_002',
    source_agent_id: 'agent-alpha',
    source_context: 'architecture doc',
    observed_at: '2026-03-01T11:35:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['architecture'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_010',
    entity_id: 'ent_demo_002',
    content: 'Horizon API target launch date is April 15, 2026',
    confidence: 'high',
    source_receipt_id: 'rcpt_mem_002',
    source_agent_id: 'agent-alpha',
    source_context: 'roadmap review',
    observed_at: '2026-03-01T11:40:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['schedule', 'milestone'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_011',
    entity_id: 'ent_demo_002',
    content: 'Horizon API authentication uses JWT with RS256 signing',
    confidence: 'certain',
    source_receipt_id: 'rcpt_mem_010',
    source_agent_id: 'agent-alpha',
    source_context: 'security review',
    observed_at: '2026-03-04T10:15:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['security', 'auth'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_012',
    entity_id: 'ent_demo_002',
    content: 'Rate limiting set to 100 requests per minute per API key',
    confidence: 'high',
    source_receipt_id: 'rcpt_mem_011',
    source_agent_id: 'agent-beta',
    source_context: 'API design meeting',
    observed_at: '2026-03-07T15:30:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['performance', 'config'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_013',
    entity_id: 'ent_demo_002',
    content: 'Horizon API staging environment at staging.horizon.nebula.dev',
    confidence: 'medium',
    source_receipt_id: 'rcpt_mem_011',
    source_agent_id: 'agent-alpha',
    source_context: 'deployment notes',
    observed_at: '2026-03-08T11:00:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: '2026-03-25T00:00:00Z',
    tags: ['infra', 'environment'],
    metadata: {},
  },

  // PostgreSQL — 4 observations
  {
    observation_id: 'obs_demo_014',
    entity_id: 'ent_demo_003',
    content: 'PostgreSQL primary instance runs on RDS with Multi-AZ deployment',
    confidence: 'certain',
    source_receipt_id: 'rcpt_mem_003',
    source_agent_id: 'agent-beta',
    source_context: 'infra audit',
    observed_at: '2026-03-02T09:20:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['infra', 'database'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_015',
    entity_id: 'ent_demo_003',
    content: 'Connection pool size set to 20 for production workloads',
    confidence: 'high',
    source_receipt_id: 'rcpt_mem_003',
    source_agent_id: 'agent-beta',
    source_context: 'performance tuning',
    observed_at: '2026-03-02T09:25:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['config', 'performance'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_016',
    entity_id: 'ent_demo_003',
    content: 'Daily backups retained for 30 days with point-in-time recovery',
    confidence: 'certain',
    source_receipt_id: 'rcpt_mem_010',
    source_agent_id: 'agent-beta',
    source_context: 'backup policy review',
    observed_at: '2026-03-06T14:00:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['backup', 'ops'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_017',
    entity_id: 'ent_demo_003',
    content: 'Using pgvector extension for embedding similarity search',
    confidence: 'high',
    source_receipt_id: 'rcpt_mem_012',
    source_agent_id: 'agent-alpha',
    source_context: 'feature planning',
    observed_at: '2026-03-10T11:30:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['extension', 'ai'],
    metadata: {},
  },

  // Code Style — 4 observations
  {
    observation_id: 'obs_demo_018',
    entity_id: 'ent_demo_004',
    content: 'Prefer explicit return types on all exported functions',
    confidence: 'high',
    source_receipt_id: 'rcpt_mem_004',
    source_agent_id: 'agent-alpha',
    source_context: 'style guide discussion',
    observed_at: '2026-03-02T14:25:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['typescript', 'style'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_019',
    entity_id: 'ent_demo_004',
    content: 'Use single quotes for strings, no semicolons (Prettier defaults)',
    confidence: 'certain',
    source_receipt_id: 'rcpt_mem_004',
    source_agent_id: 'agent-alpha',
    source_context: 'eslint config review',
    observed_at: '2026-03-02T14:30:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['formatting', 'style'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_020',
    entity_id: 'ent_demo_004',
    content: 'Prefer named exports over default exports',
    confidence: 'medium',
    source_receipt_id: 'rcpt_mem_010',
    source_agent_id: 'agent-gamma',
    source_context: 'code review feedback',
    observed_at: '2026-03-05T16:00:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['module', 'style'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_021',
    entity_id: 'ent_demo_004',
    content: 'Maximum line length 100 characters',
    confidence: 'high',
    source_receipt_id: 'rcpt_mem_004',
    source_agent_id: 'agent-alpha',
    source_context: 'prettier config',
    observed_at: '2026-03-02T14:35:00Z',
    forgotten_at: '2026-03-15T09:00:00Z',
    forgotten_by: 'agent-alpha',
    superseded_by: null,
    expires_at: null,
    tags: ['formatting'],
    metadata: {},
  },

  // Nebula Labs — 3 observations
  {
    observation_id: 'obs_demo_022',
    entity_id: 'ent_demo_005',
    content: 'Nebula Labs uses a monorepo structure with Turborepo',
    confidence: 'certain',
    source_receipt_id: 'rcpt_mem_005',
    source_agent_id: 'agent-alpha',
    source_context: 'onboarding doc',
    observed_at: '2026-03-03T08:05:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['tooling', 'monorepo'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_023',
    entity_id: 'ent_demo_005',
    content: 'Engineering team follows two-week sprint cycles with Monday standups',
    confidence: 'high',
    source_receipt_id: 'rcpt_mem_005',
    source_agent_id: 'agent-alpha',
    source_context: 'team wiki',
    observed_at: '2026-03-03T08:10:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['process', 'agile'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_024',
    entity_id: 'ent_demo_005',
    content: 'CI/CD pipeline uses GitHub Actions with required status checks',
    confidence: 'certain',
    source_receipt_id: 'rcpt_mem_011',
    source_agent_id: 'agent-beta',
    source_context: 'pipeline review',
    observed_at: '2026-03-07T10:00:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['ci', 'devops'],
    metadata: {},
  },

  // TypeScript — 3 observations
  {
    observation_id: 'obs_demo_025',
    entity_id: 'ent_demo_006',
    content: 'TypeScript strict mode enabled across all packages',
    confidence: 'certain',
    source_receipt_id: 'rcpt_mem_006',
    source_agent_id: 'agent-gamma',
    source_context: 'tsconfig review',
    observed_at: '2026-03-03T10:50:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['config', 'typescript'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_026',
    entity_id: 'ent_demo_006',
    content: 'Using TypeScript project references for incremental builds',
    confidence: 'high',
    source_receipt_id: 'rcpt_mem_006',
    source_agent_id: 'agent-gamma',
    source_context: 'build optimization',
    observed_at: '2026-03-03T10:55:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['build', 'performance'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_027',
    entity_id: 'ent_demo_006',
    content: 'Prefer Zod for runtime validation over io-ts',
    confidence: 'high',
    source_receipt_id: 'rcpt_mem_012',
    source_agent_id: 'agent-alpha',
    source_context: 'library selection',
    observed_at: '2026-03-09T13:00:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['library', 'validation'],
    metadata: {},
  },

  // Q1 Sprint — 3 observations
  {
    observation_id: 'obs_demo_028',
    entity_id: 'ent_demo_007',
    content: 'Sprint goal: ship Horizon API v1 endpoints for external partners',
    confidence: 'certain',
    source_receipt_id: 'rcpt_mem_007',
    source_agent_id: 'agent-alpha',
    source_context: 'sprint planning',
    observed_at: '2026-03-04T09:05:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['sprint', 'goal'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_029',
    entity_id: 'ent_demo_007',
    content: 'Velocity averaged 42 story points per sprint in Q1',
    confidence: 'high',
    source_receipt_id: 'rcpt_mem_011',
    source_agent_id: 'agent-alpha',
    source_context: 'retrospective',
    observed_at: '2026-03-08T16:00:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['metrics', 'velocity'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_030',
    entity_id: 'ent_demo_007',
    content: 'Three critical bugs blocking release identified in sprint review',
    confidence: 'medium',
    source_receipt_id: 'rcpt_mem_012',
    source_agent_id: 'agent-beta',
    source_context: 'sprint review',
    observed_at: '2026-03-11T14:00:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['bugs', 'blockers'],
    metadata: {},
  },

  // Sarah Kim — 3 observations
  {
    observation_id: 'obs_demo_031',
    entity_id: 'ent_demo_008',
    content: 'Sarah is the product manager for the Horizon API project',
    confidence: 'certain',
    source_receipt_id: 'rcpt_mem_008',
    source_agent_id: 'agent-beta',
    source_context: 'team introduction',
    observed_at: '2026-03-05T11:05:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['role', 'project'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_032',
    entity_id: 'ent_demo_008',
    content: 'Sarah prefers async communication via Slack over meetings',
    confidence: 'medium',
    source_receipt_id: 'rcpt_mem_008',
    source_agent_id: 'agent-beta',
    source_context: 'working preferences',
    observed_at: '2026-03-05T11:10:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['preference', 'communication'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_033',
    entity_id: 'ent_demo_008',
    content: 'Sarah owns the partner onboarding workflow for Horizon API',
    confidence: 'high',
    source_receipt_id: 'rcpt_mem_012',
    source_agent_id: 'agent-alpha',
    source_context: 'responsibility matrix',
    observed_at: '2026-03-10T10:00:00Z',
    forgotten_at: null,
    forgotten_by: null,
    superseded_by: null,
    expires_at: null,
    tags: ['ownership', 'workflow'],
    metadata: {},
  },

  // Webpack (forgotten entity) — 2 observations
  {
    observation_id: 'obs_demo_034',
    entity_id: 'ent_demo_009',
    content: 'Webpack used for legacy bundle in the dashboard app',
    confidence: 'medium',
    source_receipt_id: 'rcpt_mem_009',
    source_agent_id: 'agent-alpha',
    source_context: 'build system audit',
    observed_at: '2026-03-06T15:05:00Z',
    forgotten_at: '2026-03-20T16:00:00Z',
    forgotten_by: 'agent-alpha',
    superseded_by: null,
    expires_at: null,
    tags: ['build', 'legacy'],
    metadata: {},
  },
  {
    observation_id: 'obs_demo_035',
    entity_id: 'ent_demo_009',
    content: 'Migration from Webpack to Vite planned for Q2 2026',
    confidence: 'high',
    source_receipt_id: 'rcpt_mem_009',
    source_agent_id: 'agent-alpha',
    source_context: 'migration plan',
    observed_at: '2026-03-06T15:10:00Z',
    forgotten_at: '2026-03-20T16:00:00Z',
    forgotten_by: 'agent-alpha',
    superseded_by: null,
    expires_at: null,
    tags: ['migration', 'build'],
    metadata: {},
  },
]

// ─── Relationships ──────────────────────────────────────────────────────────

export const DEMO_RELATIONSHIPS: Relationship[] = [
  {
    relationship_id: 'rel_demo_001',
    from_entity_id: 'ent_demo_001', // Alex Chen
    to_entity_id: 'ent_demo_002',   // Horizon API
    relationship_type: 'leads',
    strength: 'certain',
    source_receipt_id: 'rcpt_mem_001',
    created_at: '2026-03-01T10:15:00Z',
    forgotten_at: null,
    metadata: {},
  },
  {
    relationship_id: 'rel_demo_002',
    from_entity_id: 'ent_demo_002', // Horizon API
    to_entity_id: 'ent_demo_003',   // PostgreSQL
    relationship_type: 'uses',
    strength: 'certain',
    source_receipt_id: 'rcpt_mem_003',
    created_at: '2026-03-02T09:30:00Z',
    forgotten_at: null,
    metadata: {},
  },
  {
    relationship_id: 'rel_demo_003',
    from_entity_id: 'ent_demo_001', // Alex Chen
    to_entity_id: 'ent_demo_005',   // Nebula Labs
    relationship_type: 'works_at',
    strength: 'certain',
    source_receipt_id: 'rcpt_mem_005',
    created_at: '2026-03-03T08:15:00Z',
    forgotten_at: null,
    metadata: {},
  },
  {
    relationship_id: 'rel_demo_004',
    from_entity_id: 'ent_demo_002', // Horizon API
    to_entity_id: 'ent_demo_005',   // Nebula Labs
    relationship_type: 'owned_by',
    strength: 'certain',
    source_receipt_id: 'rcpt_mem_005',
    created_at: '2026-03-03T08:20:00Z',
    forgotten_at: null,
    metadata: {},
  },
  {
    relationship_id: 'rel_demo_005',
    from_entity_id: 'ent_demo_002', // Horizon API
    to_entity_id: 'ent_demo_006',   // TypeScript
    relationship_type: 'built_with',
    strength: 'high',
    source_receipt_id: 'rcpt_mem_006',
    created_at: '2026-03-03T11:00:00Z',
    forgotten_at: null,
    metadata: {},
  },
  {
    relationship_id: 'rel_demo_006',
    from_entity_id: 'ent_demo_008', // Sarah Kim
    to_entity_id: 'ent_demo_002',   // Horizon API
    relationship_type: 'manages',
    strength: 'high',
    source_receipt_id: 'rcpt_mem_008',
    created_at: '2026-03-05T11:15:00Z',
    forgotten_at: null,
    metadata: {},
  },
  {
    relationship_id: 'rel_demo_007',
    from_entity_id: 'ent_demo_007', // Q1 Sprint
    to_entity_id: 'ent_demo_002',   // Horizon API
    relationship_type: 'targets',
    strength: 'high',
    source_receipt_id: 'rcpt_mem_007',
    created_at: '2026-03-04T09:10:00Z',
    forgotten_at: null,
    metadata: {},
  },
  {
    relationship_id: 'rel_demo_008',
    from_entity_id: 'ent_demo_008', // Sarah Kim
    to_entity_id: 'ent_demo_005',   // Nebula Labs
    relationship_type: 'works_at',
    strength: 'certain',
    source_receipt_id: 'rcpt_mem_008',
    created_at: '2026-03-05T11:20:00Z',
    forgotten_at: null,
    metadata: {},
  },
]

// ─── Memory Receipts ────────────────────────────────────────────────────────

export const DEMO_MEMORY_RECEIPTS: ActionReceipt[] = [
  {
    receipt_id: 'rcpt_mem_001',
    parent_receipt_id: null,
    chain_id: 'chain_mem_01',
    receipt_type: 'memory',
    agent_id: 'agent-alpha',
    org_id: 'demo-org',
    action: 'memory.observe',
    input_hash: 'sha256:mem001a1b2c3d4e5f',
    output_hash: 'sha256:mem001f6e5d4c3b2a',
    output_summary: 'Created entity Alex Chen and recorded initial observations',
    model: null,
    tokens_in: null,
    tokens_out: null,
    cost_usd: null,
    latency_ms: 12,
    tool_calls: null,
    timestamp: '2026-03-01T10:00:00Z',
    completed_at: '2026-03-01T10:00:01Z',
    status: 'completed',
    error: null,
    environment: 'production',
    tags: ['memory', 'observe'],
    constraints: null,
    constraint_result: null,
    signature: 'ed25519:demo_signature',
    verify_url: 'local://verify/rcpt_mem_001',
    callback_verified: null,
    confidence: null,
    metadata: { memory_operation: 'observe', entity_id: 'ent_demo_001', scope: 'user' },
  },
  {
    receipt_id: 'rcpt_mem_002',
    parent_receipt_id: null,
    chain_id: 'chain_mem_01',
    receipt_type: 'memory',
    agent_id: 'agent-alpha',
    org_id: 'demo-org',
    action: 'memory.observe',
    input_hash: 'sha256:mem002a1b2c3d4e5f',
    output_hash: 'sha256:mem002f6e5d4c3b2a',
    output_summary: 'Created entity Horizon API with architecture observations',
    model: null,
    tokens_in: null,
    tokens_out: null,
    cost_usd: null,
    latency_ms: 8,
    tool_calls: null,
    timestamp: '2026-03-01T11:30:00Z',
    completed_at: '2026-03-01T11:30:01Z',
    status: 'completed',
    error: null,
    environment: 'production',
    tags: ['memory', 'observe'],
    constraints: null,
    constraint_result: null,
    signature: 'ed25519:demo_signature',
    verify_url: 'local://verify/rcpt_mem_002',
    callback_verified: null,
    confidence: null,
    metadata: { memory_operation: 'observe', entity_id: 'ent_demo_002', scope: 'team' },
  },
  {
    receipt_id: 'rcpt_mem_003',
    parent_receipt_id: null,
    chain_id: 'chain_mem_02',
    receipt_type: 'memory',
    agent_id: 'agent-beta',
    org_id: 'demo-org',
    action: 'memory.observe',
    input_hash: 'sha256:mem003a1b2c3d4e5f',
    output_hash: 'sha256:mem003f6e5d4c3b2a',
    output_summary: 'Created entity PostgreSQL with infrastructure details',
    model: null,
    tokens_in: null,
    tokens_out: null,
    cost_usd: null,
    latency_ms: 10,
    tool_calls: null,
    timestamp: '2026-03-02T09:15:00Z',
    completed_at: '2026-03-02T09:15:01Z',
    status: 'completed',
    error: null,
    environment: 'production',
    tags: ['memory', 'observe'],
    constraints: null,
    constraint_result: null,
    signature: 'ed25519:demo_signature',
    verify_url: 'local://verify/rcpt_mem_003',
    callback_verified: null,
    confidence: null,
    metadata: { memory_operation: 'observe', entity_id: 'ent_demo_003', scope: 'team' },
  },
  {
    receipt_id: 'rcpt_mem_004',
    parent_receipt_id: null,
    chain_id: 'chain_mem_02',
    receipt_type: 'memory',
    agent_id: 'agent-alpha',
    org_id: 'demo-org',
    action: 'memory.observe',
    input_hash: 'sha256:mem004a1b2c3d4e5f',
    output_hash: 'sha256:mem004f6e5d4c3b2a',
    output_summary: 'Recorded code style preferences',
    model: null,
    tokens_in: null,
    tokens_out: null,
    cost_usd: null,
    latency_ms: 6,
    tool_calls: null,
    timestamp: '2026-03-02T14:20:00Z',
    completed_at: '2026-03-02T14:20:01Z',
    status: 'completed',
    error: null,
    environment: 'production',
    tags: ['memory', 'observe'],
    constraints: null,
    constraint_result: null,
    signature: 'ed25519:demo_signature',
    verify_url: 'local://verify/rcpt_mem_004',
    callback_verified: null,
    confidence: null,
    metadata: { memory_operation: 'observe', entity_id: 'ent_demo_004', scope: 'user' },
  },
  {
    receipt_id: 'rcpt_mem_005',
    parent_receipt_id: null,
    chain_id: 'chain_mem_03',
    receipt_type: 'memory',
    agent_id: 'agent-alpha',
    org_id: 'demo-org',
    action: 'memory.observe',
    input_hash: 'sha256:mem005a1b2c3d4e5f',
    output_hash: 'sha256:mem005f6e5d4c3b2a',
    output_summary: 'Created entity Nebula Labs with org details',
    model: null,
    tokens_in: null,
    tokens_out: null,
    cost_usd: null,
    latency_ms: 9,
    tool_calls: null,
    timestamp: '2026-03-03T08:00:00Z',
    completed_at: '2026-03-03T08:00:01Z',
    status: 'completed',
    error: null,
    environment: 'production',
    tags: ['memory', 'observe'],
    constraints: null,
    constraint_result: null,
    signature: 'ed25519:demo_signature',
    verify_url: 'local://verify/rcpt_mem_005',
    callback_verified: null,
    confidence: null,
    metadata: { memory_operation: 'observe', entity_id: 'ent_demo_005', scope: 'team' },
  },
  {
    receipt_id: 'rcpt_mem_006',
    parent_receipt_id: null,
    chain_id: 'chain_mem_03',
    receipt_type: 'memory',
    agent_id: 'agent-gamma',
    org_id: 'demo-org',
    action: 'memory.observe',
    input_hash: 'sha256:mem006a1b2c3d4e5f',
    output_hash: 'sha256:mem006f6e5d4c3b2a',
    output_summary: 'Recorded TypeScript configuration observations',
    model: null,
    tokens_in: null,
    tokens_out: null,
    cost_usd: null,
    latency_ms: 7,
    tool_calls: null,
    timestamp: '2026-03-03T10:45:00Z',
    completed_at: '2026-03-03T10:45:01Z',
    status: 'completed',
    error: null,
    environment: 'production',
    tags: ['memory', 'observe'],
    constraints: null,
    constraint_result: null,
    signature: 'ed25519:demo_signature',
    verify_url: 'local://verify/rcpt_mem_006',
    callback_verified: null,
    confidence: null,
    metadata: { memory_operation: 'observe', entity_id: 'ent_demo_006', scope: 'user' },
  },
  {
    receipt_id: 'rcpt_mem_007',
    parent_receipt_id: null,
    chain_id: 'chain_mem_04',
    receipt_type: 'memory',
    agent_id: 'agent-alpha',
    org_id: 'demo-org',
    action: 'memory.observe',
    input_hash: 'sha256:mem007a1b2c3d4e5f',
    output_hash: 'sha256:mem007f6e5d4c3b2a',
    output_summary: 'Created Q1 Sprint context entity',
    model: null,
    tokens_in: null,
    tokens_out: null,
    cost_usd: null,
    latency_ms: 5,
    tool_calls: null,
    timestamp: '2026-03-04T09:00:00Z',
    completed_at: '2026-03-04T09:00:01Z',
    status: 'completed',
    error: null,
    environment: 'production',
    tags: ['memory', 'observe'],
    constraints: null,
    constraint_result: null,
    signature: 'ed25519:demo_signature',
    verify_url: 'local://verify/rcpt_mem_007',
    callback_verified: null,
    confidence: null,
    metadata: { memory_operation: 'observe', entity_id: 'ent_demo_007', scope: 'team' },
  },
  {
    receipt_id: 'rcpt_mem_008',
    parent_receipt_id: null,
    chain_id: 'chain_mem_04',
    receipt_type: 'memory',
    agent_id: 'agent-beta',
    org_id: 'demo-org',
    action: 'memory.observe',
    input_hash: 'sha256:mem008a1b2c3d4e5f',
    output_hash: 'sha256:mem008f6e5d4c3b2a',
    output_summary: 'Created entity Sarah Kim with role info',
    model: null,
    tokens_in: null,
    tokens_out: null,
    cost_usd: null,
    latency_ms: 8,
    tool_calls: null,
    timestamp: '2026-03-05T11:00:00Z',
    completed_at: '2026-03-05T11:00:01Z',
    status: 'completed',
    error: null,
    environment: 'production',
    tags: ['memory', 'observe'],
    constraints: null,
    constraint_result: null,
    signature: 'ed25519:demo_signature',
    verify_url: 'local://verify/rcpt_mem_008',
    callback_verified: null,
    confidence: null,
    metadata: { memory_operation: 'observe', entity_id: 'ent_demo_008', scope: 'team' },
  },
  {
    receipt_id: 'rcpt_mem_009',
    parent_receipt_id: null,
    chain_id: 'chain_mem_05',
    receipt_type: 'memory',
    agent_id: 'agent-alpha',
    org_id: 'demo-org',
    action: 'memory.observe',
    input_hash: 'sha256:mem009a1b2c3d4e5f',
    output_hash: 'sha256:mem009f6e5d4c3b2a',
    output_summary: 'Created entity Webpack (later forgotten)',
    model: null,
    tokens_in: null,
    tokens_out: null,
    cost_usd: null,
    latency_ms: 7,
    tool_calls: null,
    timestamp: '2026-03-06T15:00:00Z',
    completed_at: '2026-03-06T15:00:01Z',
    status: 'completed',
    error: null,
    environment: 'production',
    tags: ['memory', 'observe'],
    constraints: null,
    constraint_result: null,
    signature: 'ed25519:demo_signature',
    verify_url: 'local://verify/rcpt_mem_009',
    callback_verified: null,
    confidence: null,
    metadata: { memory_operation: 'observe', entity_id: 'ent_demo_009', scope: 'user' },
  },
  {
    receipt_id: 'rcpt_mem_010',
    parent_receipt_id: null,
    chain_id: 'chain_mem_05',
    receipt_type: 'memory',
    agent_id: 'agent-alpha',
    org_id: 'demo-org',
    action: 'memory.recall',
    input_hash: 'sha256:mem010a1b2c3d4e5f',
    output_hash: 'sha256:mem010f6e5d4c3b2a',
    output_summary: 'Recalled observations about Alex Chen and project context',
    model: null,
    tokens_in: null,
    tokens_out: null,
    cost_usd: null,
    latency_ms: 3,
    tool_calls: null,
    timestamp: '2026-03-07T09:00:00Z',
    completed_at: '2026-03-07T09:00:01Z',
    status: 'completed',
    error: null,
    environment: 'production',
    tags: ['memory', 'recall'],
    constraints: null,
    constraint_result: null,
    signature: 'ed25519:demo_signature',
    verify_url: 'local://verify/rcpt_mem_010',
    callback_verified: null,
    confidence: null,
    metadata: { memory_operation: 'recall', query: 'Alex Chen project', results_count: 5, scope: 'user' },
  },
  {
    receipt_id: 'rcpt_mem_011',
    parent_receipt_id: null,
    chain_id: 'chain_mem_06',
    receipt_type: 'memory',
    agent_id: 'agent-beta',
    org_id: 'demo-org',
    action: 'memory.recall',
    input_hash: 'sha256:mem011a1b2c3d4e5f',
    output_hash: 'sha256:mem011f6e5d4c3b2a',
    output_summary: 'Recalled infrastructure and deployment observations',
    model: null,
    tokens_in: null,
    tokens_out: null,
    cost_usd: null,
    latency_ms: 4,
    tool_calls: null,
    timestamp: '2026-03-08T14:00:00Z',
    completed_at: '2026-03-08T14:00:01Z',
    status: 'completed',
    error: null,
    environment: 'production',
    tags: ['memory', 'recall'],
    constraints: null,
    constraint_result: null,
    signature: 'ed25519:demo_signature',
    verify_url: 'local://verify/rcpt_mem_011',
    callback_verified: null,
    confidence: null,
    metadata: { memory_operation: 'recall', query: 'infrastructure PostgreSQL', results_count: 3, scope: 'team' },
  },
  {
    receipt_id: 'rcpt_mem_012',
    parent_receipt_id: null,
    chain_id: 'chain_mem_06',
    receipt_type: 'memory',
    agent_id: 'agent-alpha',
    org_id: 'demo-org',
    action: 'memory.context',
    input_hash: 'sha256:mem012a1b2c3d4e5f',
    output_hash: 'sha256:mem012f6e5d4c3b2a',
    output_summary: 'Generated full memory context for agent session',
    model: null,
    tokens_in: null,
    tokens_out: null,
    cost_usd: null,
    latency_ms: 15,
    tool_calls: null,
    timestamp: '2026-03-10T08:00:00Z',
    completed_at: '2026-03-10T08:00:01Z',
    status: 'completed',
    error: null,
    environment: 'production',
    tags: ['memory', 'context'],
    constraints: null,
    constraint_result: null,
    signature: 'ed25519:demo_signature',
    verify_url: 'local://verify/rcpt_mem_012',
    callback_verified: null,
    confidence: null,
    metadata: { memory_operation: 'context', entities_returned: 8, observations_returned: 28, scope: 'team' },
  },
  {
    receipt_id: 'rcpt_mem_013',
    parent_receipt_id: null,
    chain_id: 'chain_mem_07',
    receipt_type: 'memory',
    agent_id: 'agent-alpha',
    org_id: 'demo-org',
    action: 'memory.forget',
    input_hash: 'sha256:mem013a1b2c3d4e5f',
    output_hash: 'sha256:mem013f6e5d4c3b2a',
    output_summary: 'Forgot observation about max line length (style preference changed)',
    model: null,
    tokens_in: null,
    tokens_out: null,
    cost_usd: null,
    latency_ms: 4,
    tool_calls: null,
    timestamp: '2026-03-15T09:00:00Z',
    completed_at: '2026-03-15T09:00:01Z',
    status: 'completed',
    error: null,
    environment: 'production',
    tags: ['memory', 'forget'],
    constraints: null,
    constraint_result: null,
    signature: 'ed25519:demo_signature',
    verify_url: 'local://verify/rcpt_mem_013',
    callback_verified: null,
    confidence: null,
    metadata: { memory_operation: 'forget', observation_id: 'obs_demo_021', entity_id: 'ent_demo_004', scope: 'user' },
  },
  {
    receipt_id: 'rcpt_mem_014',
    parent_receipt_id: null,
    chain_id: 'chain_mem_07',
    receipt_type: 'memory',
    agent_id: 'agent-alpha',
    org_id: 'demo-org',
    action: 'memory.forget',
    input_hash: 'sha256:mem014a1b2c3d4e5f',
    output_hash: 'sha256:mem014f6e5d4c3b2a',
    output_summary: 'Forgot Webpack entity and its observations (migrated to Vite)',
    model: null,
    tokens_in: null,
    tokens_out: null,
    cost_usd: null,
    latency_ms: 6,
    tool_calls: null,
    timestamp: '2026-03-20T16:00:00Z',
    completed_at: '2026-03-20T16:00:01Z',
    status: 'completed',
    error: null,
    environment: 'production',
    tags: ['memory', 'forget'],
    constraints: null,
    constraint_result: null,
    signature: 'ed25519:demo_signature',
    verify_url: 'local://verify/rcpt_mem_014',
    callback_verified: null,
    confidence: null,
    metadata: { memory_operation: 'forget_entity', entity_id: 'ent_demo_009', scope: 'user' },
  },
  {
    receipt_id: 'rcpt_mem_015',
    parent_receipt_id: null,
    chain_id: 'chain_mem_08',
    receipt_type: 'memory',
    agent_id: 'agent-gamma',
    org_id: 'demo-org',
    action: 'memory.recall',
    input_hash: 'sha256:mem015a1b2c3d4e5f',
    output_hash: 'sha256:mem015f6e5d4c3b2a',
    output_summary: 'Recalled TypeScript configuration and style preferences',
    model: null,
    tokens_in: null,
    tokens_out: null,
    cost_usd: null,
    latency_ms: 2,
    tool_calls: null,
    timestamp: '2026-03-22T10:30:00Z',
    completed_at: '2026-03-22T10:30:01Z',
    status: 'completed',
    error: null,
    environment: 'production',
    tags: ['memory', 'recall'],
    constraints: null,
    constraint_result: null,
    signature: 'ed25519:demo_signature',
    verify_url: 'local://verify/rcpt_mem_015',
    callback_verified: null,
    confidence: null,
    metadata: { memory_operation: 'recall', query: 'TypeScript style', results_count: 6, scope: 'user' },
  },
]
